title: HANDSOME
description: Hands-on Materials Science for Education
logo: <img src="https://raw.githubusercontent.com/poc-handsome/poc-handsome.github.io/master/democz_150x.gif">
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
